version: 1
services:
  - type: web
    name: visionmind-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health